version: '3.9'

services:
  backend-main:
    build:
      context: ./backend/main
    container_name: backend-main
    ports:
      - "8443:8443"
    networks:
      - app-network
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    command: >
      sh -c "java -Dlogging.config=file:/app/logback-spring.xml -jar /app/blue-rabb-0.0.1-snapshot.jar"
    logging:
      driver: "none"

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - backend-main
    volumes:
      - ./logs:/app/logs
    command: >
      sh -c "npm run start > /app/logs/frontend.log 2>&1"

networks:
  app-network:
    driver: bridge
